services:
    wishters_user.registration.form.type:
        class:  Wishters\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wishters_user_registration }

    wishters_user.profile.form.type:
        class: Wishters\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wishters_user_profile }
