<?php

namespace Wishters\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnoncePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnoncePictureRepository extends EntityRepository
{
}
