<?php

namespace Wishters\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationRepository extends EntityRepository
{
    public function findRelation($user, $followed)
    {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.followed = :followed')
            ->andWhere('a.follower = :follower')
            ->setParameters(array('followed' => $followed->getId(), 'follower' => $user->getId()))
            ->getQuery()
            ->getOneOrNullResult();

        return $query;
    }
}
